import { BLOG_POSTS } from '@/data/blog-posts'
import ServiceDetailContent from '@/components/services/service-detail'

const servicesData = {
    'cleaners': {
        title: 'Hire Indian Cleaners for Russia | Professional Cleaning Staff',
        title_ru: 'Найм уборщиков из Индии для России | Профессиональный клининговый персонал',
        metaDesc: 'Hire skilled cleaners for Russian industrial and commercial facilities. Professional cleaning staff from India with fast deployment.',
        metaDesc_ru: 'Подбор квалифицированного клинингового персонала из Индии для российских объектов. Быстрый найм и полная визовая поддержка.',
        images: ['/service-and-blog/Cleaners.jpeg', '/service-and-blog/Cleaners2.jpeg'],
        intro: 'Taha Airwaves is a leading manpower consultancy specializing in professional cleaners deployment for the Russian market. With our Moscow representative office and 500+ workers deployed, we provide trained and verified cleaning personnel for industrial, commercial, and hospitality facilities across Russia.',
        intro_ru: 'Taha Airwaves — ведущая кадровая консалтинговая компания, специализирующаяся на подборе профессиональных уборщиков для российского рынка. Через наше представительство в Москве мы предоставляем обученный и проверенный персонал для уборки промышленных, коммерческих и гостиничных объектов по всей России.',
        detailedDesc: 'Our comprehensive cleaners staffing services cater to the demands of Russian industries including hospitality, oil & gas, healthcare, construction, manufacturing, and corporate organizations.',
        detailedDesc_ru: 'Наши комплексные услуги по подбору уборщиков отвечают потребностям российской промышленности, включая гостиничный бизнес, нефтегазовый сектор, здравоохранение, строительство и производство.',
        types: ['General Cleaners – Everyday sanitation and maintenance for Russian facilities.', 'Deep Clean Specialists – Intensive cleaning for industrial and commercial spaces.', 'Janitors & Maintenance Staff – Regular cleaning, waste handling, and space upkeep.', 'Industrial Cleaners – Specialized cleaning for factories, warehouses, and construction sites.', 'Hospital & Healthcare Cleaners – Hygiene compliance roles for medical environments.', 'Hospitality & Housekeeping Teams – Hotel, resort, and guest-service cleaning professionals.'],
        types_ru: ['Уборщики общего профиля – Ежедневная санитарная обработка и обслуживание объектов.', 'Специалисты по глубокой уборке – Интенсивная уборка промышленных и коммерческих помещений.', 'Дворники и техперсонал – Регулярная уборка, вывоз мусора и содержание помещений.', 'Промышленные уборщики – Специализированная уборка заводов, складов и стройплощадок.', 'Уборщики в медучреждениях – Соблюдение гигиенических стандартов в больницах.', 'Персонал гостеприимства – Уборка в отелях, курортах и сервисных объектах.'],
        industries: ['Hospitality & Hotels', 'Healthcare', 'Construction', 'Oil & Gas', 'Manufacturing', 'Corporate Offices'],
        industries_ru: ['Гостиницы и отели', 'Здравоохранение', 'Строительство', 'Нефть и газ', 'Производство', 'Корпоративные офисы'],
        process: ['Requirement Analysis – Understanding your project scope and Russian regulatory needs.', 'Candidate Sourcing – Identifying suitable candidates from our verified talent pool.', 'Screening & Evaluation – Identity verification, background checks, skill assessments.', 'Client Matching – Sharing shortlisted profiles for final approval.', 'Documentation & Mobilization – Visa processing for Russia and departure coordination.'],
        process_ru: ['Анализ требований – Изучение масштабов проекта и российских нормативов.', 'Подбор кандидатов – Поиск подходящих кандидатов из проверенной базы.', 'Проверка и оценка – Верификация личности, опыта и навыков.', 'Согласование с клиентом – Предоставление профилей для утверждения.', 'Документация и мобилизация – Визовое оформление для России и координация выезда.'],
        benefits: ['Verified and experienced cleaners for Russian facilities', 'Industry-ready personnel trained for your environment', 'Reduced HR burden and administrative workload', 'Fast deployment to Russia with visa support', 'Full documentation and compliance handling'],
        benefits_ru: ['Проверенные и опытные уборщики для российских объектов', 'Персонал, обученный для вашей отрасли', 'Снижение HR-нагрузки и администрирования', 'Быстрое размещение в России с визовой поддержкой', 'Полное оформление документов и соответствие нормативам'],
        faqs: [{ q: 'Which regions in Russia do you deploy cleaners to?', a: 'We deploy to Moscow, St. Petersburg, Siberia, and industrial zones across Russia.' }, { q: 'Are cleaners verified before deployment?', a: 'Yes, every cleaner undergoes screening, background checks, and verification.' }, { q: 'Do you handle visa processing for Russia?', a: 'Yes, we manage complete visa processing and documentation for Russian deployment.' }],
        faqs_ru: [{ q: 'В какие регионы России вы направляете уборщиков?', a: 'Мы направляем в Москву, Санкт-Петербург, Сибирь и промышленные зоны по всей России.' }, { q: 'Проверяются ли уборщики перед размещением?', a: 'Да, каждый уборщик проходит проверку данных, квалификации и безопасности.' }, { q: 'Вы оформляете визы для России?', a: 'Да, мы полностью управляем визовым процессом и документацией для России.' }],
    },
    'all-types-of-drivers': {
        title: 'Hire Indian Drivers for Russia | Heavy & Light Vehicle Drivers',
        title_ru: 'Найм водителей из Индии для России | Водители легкового и грузового транспорта',
        metaDesc: 'Hire professional drivers including truck, bus, and commercial drivers for Russia and global markets. Verified licenses and fast recruitment process.',
        metaDesc_ru: 'Наймите профессиональных водителей, включая грузовые, автобусные и коммерческие категории, для России и международных рынков. Проверенные лицензии и быстрый процесс найма.',
        images: ['/service-and-blog/drivers.jpeg', '/service-and-blog/drivers.jpeg'],
        intro: 'Taha Airwaves provides professional drivers of all categories for deployment across Russia — from light vehicles to heavy construction equipment, logistics transport, and executive services.',
        intro_ru: 'Taha Airwaves предоставляет профессиональных водителей всех категорий для работы в России — от лёгкого транспорта до тяжёлой строительной техники, логистики и представительских услуг.',
        detailedDesc: 'Our driver manpower solutions meet the operational demands of Russian construction sites, logistics companies, oil & gas operations, and corporate transport needs.',
        detailedDesc_ru: 'Наши кадровые решения для водителей отвечают потребностям российских строительных площадок, логистических компаний, нефтегазовых операций и корпоративного транспорта.',
        types: ['Light Vehicle Drivers – Corporate transport and staff mobility.', 'Heavy Vehicle Drivers – Trucks, trailers, and tankers.', 'Bus Drivers – Workforce and institutional transport.', 'Construction Vehicle Drivers – Heavy equipment on-site.', 'Delivery & Commercial Drivers – Distribution and supply chain.', 'Executive Chauffeurs – VIP and corporate transport.'],
        types_ru: ['Водители лёгкого транспорта – Корпоративные перевозки и мобильность персонала.', 'Водители тяжёлого транспорта – Грузовики, прицепы и цистерны.', 'Водители автобусов – Рабочие и институциональные перевозки.', 'Водители строительной техники – Тяжёлое оборудование на площадке.', 'Водители доставки – Дистрибуция и цепочки поставок.', 'Представительские водители – VIP и корпоративный транспорт.'],
        industries: ['Construction', 'Oil & Gas', 'Logistics & Supply Chain', 'Corporate', 'Manufacturing'],
        industries_ru: ['Строительство', 'Нефть и газ', 'Логистика', 'Корпорации', 'Производство'],
        process: ['Requirement Understanding – Vehicle category, experience, compliance.', 'Sourcing & Screening – From our verified talent pool.', 'License & Background Verification – Driving licenses validated.', 'Client Approval – Profiles for final selection.', 'Documentation & Mobilization – Visa processing and travel to Russia.'],
        process_ru: ['Анализ требований – Категория ТС, опыт, соответствие.', 'Подбор и проверка – Из нашей проверенной базы.', 'Верификация прав – Проверка водительских удостоверений.', 'Согласование с клиентом – Профили для утверждения.', 'Документация и мобилизация – Визовое оформление и выезд в Россию.'],
        benefits: ['Licensed drivers for Russian roads', 'Heavy and light vehicle specialists', 'Fast deployment with visa support', 'Verified driving history and records', 'Complete compliance handling'],
        benefits_ru: ['Лицензированные водители для российских дорог', 'Специалисты по тяжёлому и лёгкому транспорту', 'Быстрое размещение с визовой поддержкой', 'Проверенная история вождения', 'Полное оформление документов'],
        faqs: [{ q: 'Do you supply heavy truck drivers for Russia?', a: 'Yes, we supply experienced heavy vehicle drivers for construction and logistics in Russia.' }, { q: 'Do you verify driving licenses?', a: 'Yes, all driving licenses are validated per vehicle category and Russian requirements.' }],
        faqs_ru: [{ q: 'Вы поставляете водителей для тяжёлого транспорта в Россию?', a: 'Да, мы предоставляем опытных водителей тяжёлого транспорта для строительства и логистики в России.' }, { q: 'Вы проверяете водительские права?', a: 'Да, все водительские удостоверения проверяются по категории транспорта и российским требованиям.' }],
    },
    'general-labour': {
        title: 'Hire Indian General Labour for Russia | Indian Skilled Workforce Supply',
        title_ru: 'Найм разнорабочих из Индии для России | Поставка квалифицированной рабочей силы',
        metaDesc: 'Hire reliable Indian general labour for construction, logistics, and industrial projects in Russia and GCC with fast deployment and verified workforce.',
        metaDesc_ru: 'Наймите надежных разнорабочих из Индии для строительства, логистики и промышленных проектов в России и странах GCC с быстрым подбором и проверенными кандидатами.',
        images: ['/service-and-blog/General-labours.jpeg', '/service-and-blog/General-labours.jpeg'],
        intro: 'Taha Airwaves specializes in recruiting and deploying skilled, reliable general labourers for Russian construction sites, industrial facilities, warehouses, and infrastructure projects.',
        intro_ru: 'Taha Airwaves специализируется на подборе и размещении надёжных разнорабочих для российских строительных площадок, промышленных объектов, складов и инфраструктурных проектов.',
        detailedDesc: 'We provide disciplined, physically fit, and task-ready workers for large-scale operations across Russia.',
        detailedDesc_ru: 'Мы предоставляем дисциплинированных, физически подготовленных работников для масштабных операций по всей России.',
        types: ['Construction Labourers – Civil works and site preparation.', 'Warehouse & Loading Workers – Cargo handling and sorting.', 'Factory Helpers – Production line assistance.', 'Industrial Site Workers – Oil & gas and engineering.', 'Maintenance Labour – Repairs and facility upkeep.'],
        types_ru: ['Строительные рабочие – Общестроительные работы и подготовка площадок.', 'Складские и грузовые работники – Обработка грузов и сортировка.', 'Помощники на заводе – Помощь на производственных линиях.', 'Промышленные работники – Нефтегаз и инженерные проекты.', 'Обслуживающий персонал – Ремонт и содержание объектов.'],
        industries: ['Construction', 'Oil & Gas', 'Manufacturing', 'Logistics', 'Healthcare'],
        industries_ru: ['Строительство', 'Нефть и газ', 'Производство', 'Логистика', 'Здравоохранение'],
        process: ['Requirement Assessment – Project scope and Russian regulations.', 'Candidate Sourcing – From our verified database.', 'Screening & Fitness Check – Physical capability and safety.', 'Documentation & Compliance – Visa coordination for Russia.', 'Mobilization & Deployment – Travel and site placement.'],
        process_ru: ['Оценка требований – Масштаб проекта и нормативы РФ.', 'Подбор кандидатов – Из проверенной базы данных.', 'Проверка и фитнес-тест – Физические способности и безопасность.', 'Документация – Визовая координация для России.', 'Мобилизация и размещение – Поездка и интеграция на объекте.'],
        benefits: ['Physically fit workers for Russian projects', 'Professionally screened workforce', 'Quick deployment to Russia', 'Compliance with Russian labour standards', 'Industry-specific customization'],
        benefits_ru: ['Физически подготовленные работники для российских проектов', 'Профессионально проверенный персонал', 'Быстрое размещение в России', 'Соответствие российским трудовым стандартам', 'Адаптация под конкретную отрасль'],
        faqs: [{ q: 'Where in Russia do you deploy general labour?', a: 'We deploy to Moscow, Siberia, Far East, and all major industrial zones.' }, { q: 'Are workers screened before deployment?', a: 'Yes, all candidates undergo screening, verification, and fitness evaluation.' }],
        faqs_ru: [{ q: 'Куда в России вы направляете разнорабочих?', a: 'В Москву, Сибирь, Дальний Восток и все крупные промзоны.' }, { q: 'Проверяются ли работники перед размещением?', a: 'Да, все кандидаты проходят проверку данных, квалификации и физической подготовки.' }],
    },
    'loading-unloading-workers': {
        title: 'Indian Loading & Unloading Workers for Russia | Warehouse Labour Supply',
        title_ru: 'Работники по погрузке и разгрузке из Индии для России | Складская рабочая сила',
        metaDesc: 'Hire skilled loading & unloading workers from India for Russian logistics, warehousing, and construction with fast deployment.',
        metaDesc_ru: 'Подбор грузчиков из Индии для логистических, складских и строительных проектов в России с быстрым размещением.',
        images: ['/service-and-blog/Loading-unloading-workers.jpeg', '/service-and-blog/Loading-unloading-workers2.jpeg'],
        intro: 'Taha Airwaves provides verified and deployment-ready loading & unloading workers for Russian logistics operations, warehouses, construction sites, and distribution centres.',
        intro_ru: 'Taha Airwaves предоставляет проверенных и готовых к работе грузчиков для российских логистических операций, складов, строительных площадок и распределительных центров.',
        detailedDesc: 'Our loading and unloading manpower services support logistics firms, warehousing companies, and construction operations across Russia.',
        detailedDesc_ru: 'Наши услуги по подбору грузчиков обеспечивают логистические компании, складские предприятия и строительные площадки по всей России.',
        types: ['Cargo Loaders & Unloaders – Manual handling of shipments.', 'Warehouse Loading Staff – Sorting, stacking, and organizing.', 'Material Movers – Transferring materials between zones.', 'Palletizers – Arranging products for dispatch.'],
        types_ru: ['Грузчики – Ручная обработка грузов и отгрузок.', 'Складской персонал – Сортировка, укладка и организация.', 'Перевозчики материалов – Перемещение между зонами.', 'Паллетизаторы – Подготовка продукции к отправке.'],
        industries: ['Logistics', 'Manufacturing', 'Construction', 'Oil & Gas', 'Retail'],
        industries_ru: ['Логистика', 'Производство', 'Строительство', 'Нефть и газ', 'Розничная торговля'],
        process: ['Requirement Assessment – Scope and safety needs.', 'Candidate Sourcing – Verified talent pool.', 'Screening – Background and safety checks.', 'Documentation – Visa processing for Russia.', 'Deployment – Travel and on-site integration.'],
        process_ru: ['Оценка требований – Масштаб и требования безопасности.', 'Подбор кандидатов – Из проверенной базы.', 'Проверка – Безопасность и данные.', 'Документация – Визовое оформление для России.', 'Размещение – Поездка и интеграция на объекте.'],
        benefits: ['Disciplined and verified workers', 'Safety-oriented workforce', 'Fast deployment to Russia', 'Flexible solutions for all project types'],
        benefits_ru: ['Дисциплинированные и проверенные работники', 'Персонал, ориентированный на безопасность', 'Быстрое размещение в России', 'Гибкие решения для любых проектов'],
        faqs: [{ q: 'Do you deploy loading workers to Russia?', a: 'Yes, we deploy verified loading and unloading workers across Russia.' }, { q: 'Are workers physically assessed?', a: 'Yes, we assess physical capability and fitness.' }],
        faqs_ru: [{ q: 'Вы направляете грузчиков в Россию?', a: 'Да, мы размещаем проверенных грузчиков по всей России.' }, { q: 'Проходят ли работники физическую оценку?', a: 'Да, мы оцениваем физические способности и подготовку.' }],
    },
    'factory-helpers': {
        title: 'Indian Factory Workers for Russia | Hire Indian Skilled Factory Helpers',
        title_ru: 'Рабочие на фабрики из Индии для России | Найм квалифицированных фабричных работников',
        metaDesc: 'Hire skilled Indian factory workers and helpers for Russian manufacturing plants. Verified, trained, and deployment-ready.',
        metaDesc_ru: 'Подбор квалифицированных фабричных работников из Индии для российских заводов. Проверенные, обученные и готовые к размещению.',
        images: ['/service-and-blog/Factory-helpers.jpeg', '/service-and-blog/Factory-helpers2.jpeg'],
        intro: 'Taha Airwaves provides professional factory helpers for Russian manufacturing plants, production lines, and industrial facilities. Our workers are trained, verified, and deployment-ready.',
        intro_ru: 'Taha Airwaves предоставляет профессиональных помощников для российских заводов, производственных линий и промышленных объектов. Наши работники обучены, проверены и готовы к размещению.',
        detailedDesc: 'Our recruitment expertise focuses on delivering dependable, task-ready factory helpers for Russian manufacturing and industrial sectors.',
        detailedDesc_ru: 'Наша экспертиза подбора сосредоточена на предоставлении надёжных помощников для российского производственного и промышленного секторов.',
        types: ['Production Line Helpers – Assembly and manufacturing.', 'Machine Operation Assistants – CNC and industrial machinery.', 'Material Handling Helpers – Raw material management.', 'Quality Check Assistants – Product inspection.', 'Plant Maintenance Helpers – Facility upkeep.'],
        types_ru: ['Помощники на конвейере – Сборка и производство.', 'Ассистенты операторов станков – ЧПУ и промоборудование.', 'Грузчики материалов – Управление сырьём.', 'Ассистенты контроля качества – Инспекция продукции.', 'Обслуживающий персонал – Содержание предприятия.'],
        industries: ['Manufacturing', 'Logistics', 'Construction', 'Oil & Gas', 'Healthcare'],
        industries_ru: ['Производство', 'Логистика', 'Строительство', 'Нефть и газ', 'Здравоохранение'],
        process: ['Requirement Assessment – Factory needs analysis.', 'Candidate Sourcing – Verified talent pool.', 'Skill & Safety Screening – Evaluation.', 'Documentation – Visa coordination for Russia.', 'Deployment – Travel and site integration.'],
        process_ru: ['Оценка требований – Анализ нужд завода.', 'Подбор кандидатов – Из проверенной базы.', 'Оценка квалификации – Проверка навыков.', 'Документация – Визовая координация для России.', 'Размещение – Поездка и интеграция.'],
        benefits: ['Skilled, task-ready factory workers', 'Safety-aware workforce', 'Complete documentation for Russia', 'Flexible solutions for all project durations'],
        benefits_ru: ['Квалифицированные работники для заводов', 'Персонал, знающий технику безопасности', 'Полная документация для России', 'Гибкие решения на любой срок проекта'],
        faqs: [{ q: 'Do you provide factory helpers for Russia?', a: 'Yes, we deploy trained factory helpers across Russian industrial zones.' }, { q: 'Are they screened for safety?', a: 'Yes, all candidates undergo skill and safety checks.' }],
        faqs_ru: [{ q: 'Вы предоставляете помощников для российских заводов?', a: 'Да, мы размещаем обученных помощников по всей промышленной зоне России.' }, { q: 'Проверяются ли они на безопасность?', a: 'Да, все кандидаты проходят проверку навыков и безопасности.' }],
    },
    'barista': {
        title: 'Skilled Barista Workers Manpower Services',
        title_ru: 'Услуги по подбору бариста',
        metaDesc: 'Hire skilled barista and cafe staff for Russian hospitality sector.',
        metaDesc_ru: 'Подбор бариста и персонала кафе для российского гостиничного сектора.',
        images: ['/service-and-blog/Barista-workers.jpeg', '/service-and-blog/Barista-workers.jpeg'],
        intro: 'Taha Airwaves provides experienced barista workers and cafe staff for Russian hospitality businesses, hotels, restaurants, and corporate food courts.',
        intro_ru: 'Taha Airwaves предоставляет опытных бариста и персонал кафе для российского гостиничного бизнеса, отелей, ресторанов и корпоративных фуд-кортов.',
        detailedDesc: 'Our barista workers are trained in specialty coffee preparation, customer service standards, and high-volume cafe operations.',
        detailedDesc_ru: 'Наши бариста обучены приготовлению кофе, стандартам обслуживания и работе в загруженных кафе.',
        types: ['Café Baristas – Specialty coffee and beverages.', 'Hotel Baristas – High-end hospitality.', 'Event Baristas – Corporate events and catering.', 'Retail Coffee Staff – Busy café environments.'],
        types_ru: ['Бариста в кафе – Спецкофе и напитки.', 'Бариста в отелях – Премиальное гостеприимство.', 'Бариста для мероприятий – Корпоративные ивенты.', 'Персонал кофеен – Загруженные кафе.'],
        industries: ['Coffee Shops & Cafes', 'Hotels & Resorts', 'Restaurants', 'Corporate Food Courts'],
        industries_ru: ['Кофейни и кафе', 'Отели и курорты', 'Рестораны', 'Корпоративные фуд-корты'],
        process: ['Requirement Understanding – Service style and skills.', 'Candidate Sourcing – Hospitality talent pool.', 'Skill Assessment – Coffee and service evaluation.', 'Client Review – Profile selection.', 'Documentation & Deployment – Visa and travel to Russia.'],
        process_ru: ['Анализ требований – Стиль сервиса.', 'Подбор – Из базы гостиничного персонала.', 'Оценка навыков – Кофе и обслуживание.', 'Согласование – Выбор профилей.', 'Документация и размещение – Виза и поездка в Россию.'],
        benefits: ['Pre-trained barista workforce', 'Specialty coffee skills', 'Russia deployment-ready', 'Flexible staffing solutions'],
        benefits_ru: ['Обученные бариста', 'Навыки спецкофе', 'Готовность к размещению в России', 'Гибкие кадровые решения'],
        faqs: [{ q: 'Do you supply barista workers to Russia?', a: 'Yes, we deploy trained baristas to Russian hospitality businesses.' }, { q: 'Are they trained in specialty coffee?', a: 'Yes, all baristas have verified coffee preparation skills.' }],
        faqs_ru: [{ q: 'Вы предоставляете бариста в Россию?', a: 'Да, мы размещаем обученных бариста в российском гостиничном бизнесе.' }, { q: 'Они обучены спецкофе?', a: 'Да, все бариста имеют подтверждённые навыки приготовления кофе.' }],
    },
    'packing-workers': {
        title: 'Skilled Packing Workers Manpower Services',
        title_ru: 'Услуги по подбору упаковщиков',
        metaDesc: 'Hire skilled packing workers for Russian warehousing and logistics.',
        metaDesc_ru: 'Подбор упаковщиков для российских складов и логистики.',
        images: ['/service-and-blog/Packers-workers.jpeg', '/service-and-blog/Packers-workers.jpeg'],
        intro: 'Taha Airwaves provides professional packing workers for Russian warehouses, manufacturing facilities, and logistics operations.',
        intro_ru: 'Taha Airwaves предоставляет профессиональных упаковщиков для российских складов, производственных предприятий и логистических операций.',
        detailedDesc: 'We specialize in sourcing verified packing workers with expertise in packing, sorting, quality inspection, and material preparation for the Russian market.',
        detailedDesc_ru: 'Мы специализируемся на подборе проверенных упаковщиков с навыками упаковки, сортировки и подготовки материалов для российского рынка.',
        types: ['General Packing Workers – Packing, sealing, labeling.', 'Quality Control Staff – Inspection before packing.', 'Container Packing Labour – Pallets and containers.', 'Documentation Helpers – Labeling and shipping prep.'],
        types_ru: ['Упаковщики – Упаковка, герметизация, маркировка.', 'Контролёры качества – Инспекция перед упаковкой.', 'Контейнерная упаковка – Паллеты и контейнеры.', 'Помощники по документации – Маркировка и подготовка к отправке.'],
        industries: ['Logistics', 'Manufacturing', 'Construction', 'Oil & Gas', 'Retail'],
        industries_ru: ['Логистика', 'Производство', 'Строительство', 'Нефть и газ', 'Розничная торговля'],
        process: ['Requirement Assessment – Packing needs.', 'Candidate Sourcing – Verified pool.', 'Screening – Task-specific checks.', 'Documentation – Visa for Russia.', 'Deployment – Travel and integration.'],
        process_ru: ['Оценка требований – Потребности в упаковке.', 'Подбор кандидатов – Проверенная база.', 'Проверка – Проверка навыков.', 'Документация – Виза для России.', 'Размещение – Поездка и интеграция.'],
        benefits: ['Verified packing workforce', 'Attention to quality standards', 'Fast Russia deployment', 'Flexible for seasonal needs'],
        benefits_ru: ['Проверенные упаковщики', 'Внимание к стандартам качества', 'Быстрое размещение в России', 'Гибкость для сезонных нужд'],
        faqs: [{ q: 'Do you supply packing workers to Russia?', a: 'Yes, we deploy verified packing workers to Russian logistics and manufacturing facilities.' }],
        faqs_ru: [{ q: 'Вы поставляете упаковщиков в Россию?', a: 'Да, мы размещаем проверенных упаковщиков на российских логистических и производственных объектах.' }],
    },
    'emigration-immigration-clearance': {
        title: 'Visa & Immigration Services for Workers',
        title_ru: 'Визовые и иммиграционные услуги для работников',
        metaDesc: 'Complete visa processing, emigration clearance and immigration support for Indian workers deploying to Russia.',
        metaDesc_ru: 'Полное визовое оформление, эмиграционное и иммиграционное оформление для индийских работников, направляемых в Россию.',
        images: ['/service-and-blog/Immigration-clearance.jpeg', '/service-and-blog/Immigration-clearance2.jpeg'],
        intro: 'Taha Airwaves delivers end-to-end emigration and immigration clearance services for Indian workers deploying to Russia, ensuring full compliance with both Indian and Russian regulatory frameworks.',
        intro_ru: 'Taha Airwaves обеспечивает полный цикл эмиграционного и иммиграционного оформления для индийских работников, направляемых в Россию, с полным соответствием нормативам Индии и России.',
        detailedDesc: 'Our compliance process ensures documentation accuracy, verified candidate records, and alignment with requirements of both India and Russia.',
        detailedDesc_ru: 'Наш процесс соответствия обеспечивает точность документации, проверенные данные кандидатов и соответствие требованиям обеих стран.',
        types: ['Emigration Clearance – POE registration and Indian compliance.', 'Immigration Documentation – Russian visa and work permit processing.', 'Contract Validation – Employment contract review.', 'Regulatory Submissions – Government liaison.', 'Bulk Workforce Clearance – Large-scale deployment documentation.'],
        types_ru: ['Эмиграционное оформление – Регистрация POE и индийское соответствие.', 'Иммиграционная документация – Российская виза и разрешение на работу.', 'Валидация контрактов – Проверка трудовых договоров.', 'Нормативные заявки – Связь с госорганами.', 'Массовое оформление – Документация для крупных партий.'],
        industries: ['All Russia-Bound Employment', 'Construction', 'Oil & Gas', 'Manufacturing', 'Facilities Management'],
        industries_ru: ['Все направления в Россию', 'Строительство', 'Нефть и газ', 'Производство', 'Управление объектами'],
        process: ['Document Collection – Worker and employer documents.', 'Verification – Cross-checking records.', 'Regulatory Submission – Filing with authorities.', 'Status Tracking – Progress monitoring.', 'Final Clearance – Completing formalities.'],
        process_ru: ['Сбор документов – Документы работника и работодателя.', 'Верификация – Перекрёстная проверка данных.', 'Подача в органы – Подача в компетентные органы.', 'Отслеживание статуса – Мониторинг прогресса.', 'Финальное оформление – Завершение формальностей.'],
        benefits: ['Process-driven clearance framework', 'Compliance across India and Russia', 'Transparent timelines', 'Accountability at every stage'],
        benefits_ru: ['Системный процесс оформления', 'Соответствие нормативам Индии и России', 'Прозрачные сроки', 'Ответственность на каждом этапе'],
        faqs: [{ q: 'Do you handle Russian immigration clearance?', a: 'Yes, we coordinate complete immigration documentation and compliance for Russia.' }],
        faqs_ru: [{ q: 'Вы оформляете российскую иммиграцию?', a: 'Да, мы координируем полное иммиграционное оформление и соответствие для России.' }],
    },
    'document-attestation-services': {
        title: 'Document Attestation Services',
        title_ru: 'Аттестация документов',
        metaDesc: 'Professional document attestation for Russian workforce deployment.',
        metaDesc_ru: 'Профессиональная аттестация документов для размещения персонала в России.',
        images: ['/service-and-blog/Document-attestation.jpeg', '/service-and-blog/Document-attestation.jpeg'],
        intro: 'Taha Airwaves provides complete document attestation services for workers deploying to Russia, ensuring all documents are authenticated and recognized by relevant authorities.',
        intro_ru: 'Taha Airwaves предоставляет полные услуги по аттестации документов для работников, направляемых в Россию, обеспечивая аутентификацию и признание всех документов.',
        detailedDesc: 'The service ensures lawful deployment by authenticating educational, professional, and employment documents.',
        detailedDesc_ru: 'Услуга обеспечивает законное размещение путём аутентификации образовательных, профессиональных и трудовых документов.',
        types: ['Educational Certificates – Degree and diploma attestation.', 'Professional Qualifications – Trade certificates.', 'Experience Certificates – Employment validation.', 'Employment Contracts – Contract legalization.'],
        types_ru: ['Образовательные сертификаты – Аттестация дипломов.', 'Профессиональные квалификации – Торговые сертификаты.', 'Свидетельства об опыте – Валидация трудового стажа.', 'Трудовые договоры – Легализация контрактов.'],
        industries: ['All Industries', 'Construction', 'Oil & Gas', 'Healthcare', 'Corporate'],
        industries_ru: ['Все отрасли', 'Строительство', 'Нефть и газ', 'Здравоохранение', 'Корпорации'],
        process: ['Document Collection – Gathering originals.', 'State Authentication – HRD attestation.', 'MEA Attestation – Ministry authentication.', 'Embassy Attestation – Russian embassy.', 'Document Return – Secure delivery.'],
        process_ru: ['Сбор документов – Сбор оригиналов.', 'Государственная аттестация – Аттестация HRD.', 'Аттестация MEA – Аутентификация министерства.', 'Консульская аттестация – Посольство России.', 'Возврат документов – Безопасная доставка.'],
        benefits: ['End-to-end attestation', 'MEA and embassy handled', 'Apostille services', 'Secure document tracking'],
        benefits_ru: ['Полный цикл аттестации', 'Оформление MEA и посольства', 'Услуги апостиля', 'Безопасное отслеживание документов'],
        faqs: [{ q: 'Do you handle Russian embassy attestation?', a: 'Yes, we coordinate attestation with the Russian embassy.' }],
        faqs_ru: [{ q: 'Вы оформляете аттестацию в российском посольстве?', a: 'Да, мы координируем аттестацию с посольством России.' }],
    },
    'skilled-labourers-technicians': {
        title: 'Skilled Technicians Manpower Services',
        title_ru: 'Услуги по подбору квалифицированных техников',
        metaDesc: 'Hire skilled electricians, plumbers, welders for Russian construction.',
        metaDesc_ru: 'Подбор электриков, сантехников, сварщиков для российского строительства.',
        images: ['/service-and-blog/Factory-helpers2.jpeg', '/service-and-blog/Factory-helpers2.jpeg'],
        intro: 'Taha Airwaves provides skilled technicians — electricians, plumbers, welders, and fitters — for Russian construction sites, industrial plants, and infrastructure projects.',
        intro_ru: 'Taha Airwaves предоставляет квалифицированных техников — электриков, сантехников, сварщиков и слесарей — для российских строительных площадок и промышленных объектов.',
        detailedDesc: 'Our technicians are trade-tested, certified, and deployment-ready for Russian industrial and construction operations.',
        detailedDesc_ru: 'Наши техники прошли профтестирование, сертифицированы и готовы к работе на российских объектах.',
        types: ['Electricians – Industrial and residential wiring.', 'Plumbers – Pipeline and plumbing systems.', 'Welders – Arc, MIG, TIG welding.', 'Fitters – Mechanical and pipe fitting.'],
        types_ru: ['Электрики – Промышленная и бытовая проводка.', 'Сантехники – Трубопроводы и системы водоснабжения.', 'Сварщики – Дуговая, MIG, TIG сварка.', 'Слесари – Механическая и трубная сборка.'],
        industries: ['Construction', 'Oil & Gas', 'Manufacturing', 'Infrastructure'],
        industries_ru: ['Строительство', 'Нефть и газ', 'Производство', 'Инфраструктура'],
        process: ['Requirement Analysis – Trade and skill specifications.', 'Sourcing – Trade-tested candidates.', 'Certification Review – License and certificate checks.', 'Documentation – Russian visa processing.', 'Deployment – Travel and site placement.'],
        process_ru: ['Анализ требований – Специализация и навыки.', 'Подбор – Кандидаты с профтестированием.', 'Проверка сертификатов – Лицензии и квалификация.', 'Документация – Визовое оформление для России.', 'Размещение – Поездка и интеграция.'],
        benefits: ['Trade-tested and certified technicians', 'Experience in Russian construction', 'Full compliance and documentation', 'Fast deployment'],
        benefits_ru: ['Проверенные и сертифицированные техники', 'Опыт на российских стройках', 'Полное соответствие и документация', 'Быстрое размещение'],
        faqs: [{ q: 'Do you deploy welders to Russia?', a: 'Yes, we deploy certified welders for construction and industrial projects in Russia.' }],
        faqs_ru: [{ q: 'Вы направляете сварщиков в Россию?', a: 'Да, мы размещаем сертифицированных сварщиков на строительных и промышленных проектах в России.' }],
    },
    'employee-outsourcing-solutions': {
        title: 'Employee Outsourcing Services | Global Workforce Solutions',
        title_ru: 'Аутсорсинг персонала | Глобальные решения по рабочей силе',
        metaDesc: 'Complete employee outsourcing services with global workforce solutions for Russian employers. Staffing, payroll, and HR compliance.',
        metaDesc_ru: 'Комплексные услуги аутсорсинга персонала с глобальными решениями по рабочей силе для российских работодателей. Кадры, зарплата и HR-соответствие.',
        images: ['/service-and-blog/employe-outsourcing-.jpeg', '/service-and-blog/Employee-outsourcing2.jpeg'],
        intro: 'Taha Airwaves provides structured employee outsourcing solutions for Russian employers requiring compliant, scalable, and deployment-ready Indian manpower.',
        intro_ru: 'Taha Airwaves предоставляет структурированные решения по аутсорсингу персонала для российских работодателей, нуждающихся в соответствующей, масштабируемой индийской рабочей силе.',
        detailedDesc: 'Employee outsourcing enables Russian employers to focus on core operations while we manage recruitment, compliance, and deployment.',
        detailedDesc_ru: 'Аутсорсинг позволяет российским работодателям сосредоточиться на основной деятельности, пока мы управляем подбором, соответствием и размещением.',
        types: ['Contract Staffing – Fixed-term workforce for projects.', 'Temporary Workforce – Short-duration manpower.', 'Permanent Placement – Long-term core roles.', 'Payroll Management – Salary processing.', 'Compliance Administration – Labour law adherence.'],
        types_ru: ['Контрактный персонал – Работники на срок проекта.', 'Временный персонал – Краткосрочная рабочая сила.', 'Постоянное трудоустройство – Долгосрочные ключевые роли.', 'Управление зарплатой – Обработка выплат.', 'Администрирование соответствия – Соблюдение трудового права.'],
        industries: ['Construction', 'Oil & Gas', 'Manufacturing', 'Industrial Plants', 'Facilities Management'],
        industries_ru: ['Строительство', 'Нефть и газ', 'Производство', 'Промышленные предприятия', 'Управление объектами'],
        process: ['Workforce Assessment – Requirements and roles.', 'Recruitment & Screening – Verifying candidates.', 'Compliance & Documentation – All regulations.', 'Deployment & Mobilization – Travel to Russia.', 'Ongoing Support – Payroll and contract management.'],
        process_ru: ['Оценка потребностей – Требования и роли.', 'Подбор и проверка – Верификация кандидатов.', 'Соответствие и документация – Все нормативы.', 'Размещение и мобилизация – Поездка в Россию.', 'Текущая поддержка – Зарплата и управление контрактами.'],
        benefits: ['Centralized workforce administration', 'Compliance-driven process', 'Scalable workforce solutions', 'Reduced administrative burden', 'Dedicated Russia support'],
        benefits_ru: ['Централизованное управление кадрами', 'Процесс на основе соответствия', 'Масштабируемые кадровые решения', 'Сниженная административная нагрузка', 'Специализированная поддержка для России'],
        faqs: [{ q: 'What is employee outsourcing?', a: 'Structured deployment where recruitment, compliance, and mobilization are managed by Taha Airwaves for Russian employers.' }],
        faqs_ru: [{ q: 'Что такое аутсорсинг персонала?', a: 'Структурированное размещение, при котором подбор, соответствие и мобилизация управляются Taha Airwaves для российских работодателей.' }],
    },
}

export function generateStaticParams() {
    return Object.keys(servicesData).map((slug) => ({ slug }))
}

export async function generateMetadata({ params }) {
    const { slug } = await params
    const service = servicesData[slug] || {}
    return {
        title: `${service.title_ru || service.title || 'Услуга'}`,
        description: service.metaDesc_ru || service.metaDesc || 'Услуги по подбору персонала от Taha Airwaves.',
        openGraph: {
            title: `${service.title_ru || service.title || 'Услуга'}`,
            description: service.metaDesc_ru || service.metaDesc || 'Услуги по подбору персонала от Taha Airwaves.',
            url: `https://tahaairwaves.ru/services/${slug}`,
        },
    }
}

export default async function ServiceDetailPage({ params }) {
    const { slug } = await params
    const service = servicesData[slug]

    if (!service) {
        return (
            <div style={{ padding: '120px 24px', textAlign: 'center' }}>
                <h1 style={{ fontFamily: 'var(--font-inter)', fontSize: '2.5rem', fontWeight: 900, color: '#1A1A1A' }}>Service Not Found</h1>
                <p style={{ color: '#6B7280', margin: '16px 0 24px', fontFamily: 'var(--font-poppins)' }}>The service you are looking for does not exist.</p>
            </div>
        )
    }

    return <ServiceDetailContent service={service} />
}
