'use client'

import { createContext, useContext, useState } from 'react'

const translations = {
    ru: {
        // Navbar
        home: 'Главная',
        aboutUs: 'О нас',
        services: 'Услуги',
        blog: 'Блог',
        contactUs: 'Контакты',
        cvBuilder: 'Конструктор CV',
        whatsappUs: 'Написать в WhatsApp',
        // Hero
        heroTitle1: 'КАДРОВЫЕ',
        heroTitle2: 'РЕШЕНИЯ',
        heroTagline: 'Лицензированное кадровое агентство с офисом в Москве. Мы помогаем российским компаниям нанимать квалифицированных специалистов из Индии, Непала и Индонезии.',
        heroCtaServices: 'Получить персонал',
        heroCtaContact: 'Поговорить с экспертом (WhatsApp)',
        heroStat1Value: '500+',
        heroStat1Label: 'РАБОТНИКОВ В РОССИИ',
        heroStat2Value: '2022',
        heroStat2Label: 'РАБОТА В РОССИИ',
        heroStat3Value: '10+',
        heroStat3Label: 'ЛЕТ ОПЫТА',
        // Hero Contact Form
        formName: 'Ваше имя',
        formEmail: 'Эл. почта',
        formPhone: 'Телефон',
        formMessage: 'Сообщение',
        formSubmit: 'Отправить заявку',
        formTitle: 'Быстрая заявка',
        // About
        aboutTitle: '• О нас',
        aboutPara1: 'Ваш надёжный кадровый партнёр в России',
        aboutPara2: 'Taha Airwaves — признанная компания по подбору персонала с мировым опытом, специализирующаяся на поставке квалифицированной рабочей силы в Россию. Имеем сильные позиции в Москве и глубокое понимание российского трудового законодательства. Обеспечиваем быстрые и плавные решения по найму.',
        learnMore: 'Запросить кандидатов',
        getInTouch: 'Связаться',
        // Our Strength
        strengthTitle: 'Стратегические',
        strengthTitleAccent: 'кадровые решения',
        strengthSubtitle: 'Оптимизированный подбор с надёжным развёртыванием квалифицированного персонала за 7–15 дней.',
        metric1Value: '500+',
        metric1Label: 'Сотрудников в России',
        metric1Desc: 'Проверенные специалисты, размещённые в различных отраслях с 2022 года',
        metric2Value: '2022',
        metric2Label: 'Начало работы в России',
        metric2Desc: 'Офис в Москве, обслуживающий российский рынок',
        metric3Value: '20+',
        metric3Label: 'Лет мирового опыта',
        metric3Desc: 'Лицензированное агентство по набору персонала с 2015 года',
        metric4Value: '50+',
        metric4Label: 'Компаний-партнёров',
        metric4Desc: 'Работаем с ведущими работодателями в различных отраслях',
        // How It Works
        howTitle: 'Что нас',
        howTitleAccent: 'отличает',
        howSubtitle: 'Нанимайте лучше. Размещайте быстрее. Масштабируйтесь умнее.',
        step1Title: 'Специалисты по найму Индия—Россия',
        step1Desc: 'Целенаправленная экспертиза в подборе индийского персонала именно для России с глубоким знанием рынка.',
        step2Title: 'Персональная координация',
        step2Desc: 'Персонализированная поддержка каждого клиента для гладкой коммуникации и быстрого принятия решений.',
        step3Title: 'Быстрое размещение 7–15 дней',
        step3Desc: 'Одни из самых быстрых сроков размещения персонала в отрасли.',
        step4Title: 'Отраслевая экспертиза найма',
        step4Desc: 'Специализированные решения по подбору персонала для строительства, логистики, производства и сферы услуг.',
        step5Title: 'Проверенные и готовые к работе',
        step5Desc: 'Кандидаты отобраны, протестированы и подготовлены перед размещением для снижения рисков найма.',
        step6Title: 'Масштабируемые кадровые решения',
        step6Desc: 'Эффективное управление массовым наймом для проектов любого масштаба.',
        // What We Do
        whatTitle: 'Что нас',
        whatTitleAccent: 'отличает',
        whatSubtitle: 'Мы поставляем квалифицированный персонал из Индии в Россию — без задержек',
        svc1Title: 'Подбор персонала',
        svc1Desc: 'Комплексные решения по подбору для международных работодателей, ищущих индийских специалистов.',
        svc2Title: 'Массовый набор',
        svc2Desc: 'Высокообъёмная мобилизация рабочей силы с быстрыми сроками для крупных проектов.',
        svc3Title: 'Визы и документы',
        svc3Desc: 'Полная визовая обработка, заверение документов, эмиграционное оформление и управление соответствием.',
        svc4Title: 'Поддержка развёртывания',
        svc4Desc: 'Предвыездная подготовка, координация поездок и послеразмещённая поддержка.',
        // Countries
        countriesTitle: 'Индия —',
        countriesTitleAccent: 'Россия',
        countriesSubtitle: 'Мост между индийскими кадрами и потребностями российской промышленности',
        sourcingHub: 'Центр подбора',
        headOffice: 'Головной офис: Нью-Дели',
        deploymentPipeline: 'Канал развёртывания',
        workersDeployed: 'Работников размещено в России',
        operationsOffice: 'Офис: Москва',
        deploymentOps: 'Развёртывание и операции',
        // Industries
        industriesTitle: 'ОТРАСЛИ, КОТОРЫЕ МЫ',
        industriesTitleAccent: 'ОБСЛУЖИВАЕМ',
        industriesSubtitle: 'Специализированные кадровые решения для ключевых секторов России',
        indConstruction: 'Строительство',
        indConstructionDesc: 'Рабочие, каменщики и прорабы',
        indHospitality: 'Гостеприимство',
        indHospitalityDesc: 'Персонал отелей, уборщики и работники гостиниц',
        indLogistics: 'Логистика',
        indLogisticsDesc: 'Складские сотрудники и работники цепочки поставок',
        indHealthcare: 'Здравоохранение',
        indHealthcareDesc: 'Вспомогательный медицинский персонал',
        indManufacturing: 'Производство',
        indManufacturingDesc: 'Рабочие фабрик, операторы машин и инспекторы',
        indFacility: 'Управление объектами',
        indFacilityDesc: 'Технический персонал и операторы объектов',
        indOilGas: 'Нефть и газ',
        indOilGasDesc: 'Буровые бригады и работники нефтепровода',
        indIT: 'ИТ и телеком',
        indITDesc: 'ИТ-поддержка, сетевые техники и инженеры',
        indRetail: 'Торговля и FMCG',
        indRetailDesc: 'Торговые ассоциаты и мерчандайзеры',
        // Why Us
        whyTitle: '• Почему российские компании выбирают Taha Airwaves?',
        whyDesc: 'Лицензированное государством развёртывание проверенных кадров с полным циклом рекрутинга, визовой обработкой и соответствием — доверие работодателей по всей России.',
        whyItem1Title: 'Местная поддержка в Москве',
        whyItem1Desc: 'Собственный офис в Москве со специализированной командой для российского рынка.',
        whyItem2Title: 'Быстрый процесс найма (7–15 дней)',
        whyItem2Desc: 'Отбор, оформление документов и развёртывание за минимальные сроки.',
        whyItem3Title: 'Проверенные и квалифицированные кандидаты',
        whyItem3Desc: 'Каждый кандидат проходит тщательную проверку навыков и биографии перед размещением.',
        whyItem4Title: 'Полная документальная поддержка',
        whyItem4Desc: 'Визовое оформление, медосмотры, эмиграционное разрешение — всё под ключ.',
        whyItem5Title: 'Прозрачное ценообразование',
        whyItem5Desc: 'Чёткие и прозрачные условия без скрытых платежей.',
        whyPart2Title: 'Десятилетие доверия в развёртывании кадров для России',
        whyPart2Desc: 'С более чем 10-летним опытом в сфере зарубежного набора персонала (с 2015) и выделенной командой для России с 2022 года, Taha Airwaves заработала репутацию надёжности и скорости.',
        whyStat1Number: '500+',
        whyStat1Label: 'Работников размещено',
        whyStat2Number: '365',
        whyStat2Label: 'Дней непрерывной поддержки',
        // Testimonials
        testimonialsTitle: 'Что говорят наши',
        testimonialsTitleAccent: 'клиенты',
        testimonialsSubtitle: 'Нам доверяют работодатели по всей России',
        // Blog
        blogTitle: 'Последние',
        blogTitleAccent: 'публикации',
        blogSubtitle: 'Актуальные тренды, руководства и аналитика российского рынка',
        viewAllArticles: 'Все статьи',
        readMore: 'Читать далее',
        // CTA
        ctaSubtitle: 'НАЧНИТЕ СЕГОДНЯ',
        ctaTitle: 'Создайте свою команду — быстрее, чем когда-либо',
        ctaDesc: 'Получите проверенных кандидатов за считанные дни и продолжайте развивать свой бизнес.',
        ctaBtn1: 'Получить предложение',
        ctaBtn2: 'WhatsApp',
        // Footer
        quickLinks: 'Быстрые ссылки',
        ourServices: 'Наши услуги',
        ourOffices: 'Наши офисы',
        contact: 'Контакты',
        footerDesc: 'Лицензированное государством агентство по подбору персонала, предоставляющее профессиональные кадровые решения для российского рынка.',
        // Footer service links
        svcCleaners: 'Уборщики',
        svcDrivers: 'Водители',
        svcGeneral: 'Общий труд',
        svcFactory: 'Рабочие фабрик',
        svcTechnicians: 'Техники',
        svcVisa: 'Виза и миграция',
        svcOutsourcing: 'Аутсорсинг персонала',
        // CardCarousel section keys
        servicesOffered: 'Услуги',
        csvcSectionTitle: 'Что мы предлагаем российскому рынку',
        csvc1Title: 'Международный рекрутинг',
        csvc1Desc: 'Комплексный подбор персонала для российских работодателей, ищущих квалифицированных индийских специалистов.',
        csvc2Title: 'Массовый найм',
        csvc2Desc: 'Крупномасштабная мобилизация рабочей силы с быстрыми сроками для строительных и промышленных проектов.',
        csvc3Title: 'Виза и документы',
        csvc3Desc: 'Полная визовая обработка, заверение документов, эмиграционное оформление и соответствие — под ключ.',
        csvc4Title: 'Поддержка развёртывания',
        csvc4Desc: 'Предвыездная подготовка, координация поездок и послеразмещённая поддержка.',
        csvc5Title: 'Аутсорсинг сотрудников',
        csvc5Desc: 'Полные решения по кадровому аутсорсингу — подбор персонала, расчёт зарплат и соответствие HR.',
        csvcBottomDesc: 'От квалифицированных рабочих до массового найма для крупных проектов — полная документация, визовая обработка и поддержка развёртывания.',
        viewAllServices: 'Все услуги',
        // HomeServiceBento
        bentoTitle: 'Наш процесс рекрутинга',
        bentoStep1: 'Анализ требований',
        bentoStep1Desc: 'Изучение ваших кадровых потребностей, должностей и требований проекта для правильной стратегии найма.',
        bentoStep2: 'Поиск и отбор',
        bentoStep2Desc: 'Подбор кандидатов из лучших кадровых резервов Индии со строгим отбором и проверкой.',
        bentoStep3: 'Оценка навыков',
        bentoStep3Desc: 'Профессиональное тестирование для соответствия отраслевым стандартам и требованиям.',
        bentoStep4: 'Документация и виза',
        bentoStep4Desc: 'Полное визовое оформление, юридическое соответствие и документация для международного найма.',
        bentoStep5: 'Размещение и поездка',
        bentoStep5Desc: 'Предвыездной инструктаж, организация поездки и бесперебойное размещение на объекте.',
        bentoStep6: 'Постоянная поддержка',
        bentoStep6Desc: 'Непрерывная поддержка с чёткой коммуникацией, отчётностью и без скрытых платежей.',
        bentoCTA1: 'Нанимайте лучше. Размещайте быстрее. Масштабируйтесь умнее.',
        bentoCTA2: 'Мы поставляем квалифицированный персонал из Индии в Россию — без задержек',
        // ServicesShowcase
        sspTitle: 'Наши кадровые услуги для России',
        pSvc1Title: 'Уборщики и клининг',
        pSvc1Desc: 'Профессионально обученный персонал для отелей, больниц, коммерческих и жилых объектов России.',
        pSvc2Title: 'Водители всех категорий',
        pSvc2Desc: 'Лицензированные водители для лёгкого и тяжёлого транспорта, строительной техники и специализированного транспорта.',
        pSvc3Title: 'Разнорабочие',
        pSvc3Desc: 'Надёжные рабочие для строительных площадок, складов, заводов и инфраструктурных проектов в России.',
        pSvc4Title: 'Помощники на заводе',
        pSvc4Desc: 'Обученные ассистенты для производственных линий, упаковки, контроля качества и производственной поддержки.',
        pSvc5Title: 'Оформление эмиграции',
        pSvc5Desc: 'Полное визовое оформление, документация, эмиграционное разрешение и управление соответствием для России.',
        pSvc6Title: 'Аутсорсинг персонала',
        pSvc6Desc: 'Комплексное кадровое обеспечение — временный и постоянный штат, расчёт зарплат и соответствие.',
        hireManpower: 'Нанять персонал',
        // Industries extended
        indAgriculture: 'Сельское хозяйство',
        indAgricultureDesc: 'Сельскохозяйственные рабочие и специалисты по сбору урожая',
        indMining: 'Горнодобывающая',
        indMiningDesc: 'Горняки, взрывники и операторы',
        // CountriesWeServe additional
        additionalCountries: 'Другие рынки',
        // Sub-pages
        pageServicesTitle: 'Наши услуги',
        pageServicesSubtitle: 'Комплексные кадровые решения для российского рынка',
        pageBlogTitle: 'Журнал',
        pageBlogSubtitle: 'Аналитика российского рынка труда и руководства по развёртыванию',
        // About page
        ourServices: 'Услуги',
        aboutStatLabel1: 'Работники в России',
        aboutStatLabel2: 'Лет опыта',
        aboutStatLabel3: 'Партнёрские компании',
        aboutStatLabel4: 'Соответствие',
        missionTitle: 'Наша миссия',
        missionDesc: 'Связать огромный кадровый потенциал Индии с российским спросом на рабочую силу, обеспечивая надёжный, соответствующий и эффективный рекрутинг.',
        visionTitle: 'Наше видение',
        visionDesc: 'Стать самым надёжным агентством по подбору персонала для российского рынка, известным своей качеством, прозрачностью и комплексным обслуживанием.',
        promiseTitle: 'Наше обещание',
        promiseDesc: 'Лицензированная, прошедшая трейд тестирование и полностью документированная рабочая сила — доставленная вовремя без компромиссов.',
        // Additional services (ServicesMain)
        loadingTitle: 'Грузчики',
        loadingDesc: 'Опытные грузчики для портов, складов, фрахтовых терминалов и дистрибьюцентров.',
        baristaTitle: 'Баристы',
        baristaDesc: 'Обученные баристы для кафе, отелей, корпоративных мероприятий.',
        packersTitle: 'Упаковщики',
        packersDesc: 'Упаковка, сортировка, маркировка и контроль качества.',
        docAttestTitle: 'Аттестация документов',
        docAttestDesc: 'Аттестация через министерство, MEA и посольство для учебных, профессиональных и коммерческих документов.',
        techDesc: 'Квалифицированные техники, электрики и специалисты для строительных проектов.',
        // Contact form
        formName: 'Ваше имя',
        formEmail: 'Эл. почта',
        formPhone: 'Номер телефона',
        formSubmit: 'Отправить',

        // Chatbot
        chatWelcome: 'Здравствуйте! Я ассистент Taha Airwaves. Чем могу помочь? Буду рад помочь работодателям в подборе персонала или соискателям о доступных вакансиях.',
        chatQuick1: 'Какие услуги вы предлагаете?',
        chatQuick2: 'Как быстро происходит трудоустройство?',
        chatQuick3: 'В какие страны вы осуществляете набор?',
        chatQuick4: 'Хочу нанять работников',
        chatPlaceholder: 'Напишите сообщение...',
        chatTooltip: 'Спросите у ИИ Taha',
        chatOnline: 'ИИ-ассистент • Онлайн',
        // Partners
        partnersTitle: 'Наши',
        partnersTitleAccent: 'партнёры',
        partnersSubtitle: 'Нам доверяют ведущие компании',
        // Stats — Bento rewrite
        bentoStatTitle1: 'Taha Airwaves: Скорость',
        bentoStatDesc1: 'Быстрый найм и размещение без ущерба качеству.',
        bentoStatTitle2: 'Taha Airwaves: Качество',
        bentoStatDesc2: 'Квалифицированные, проверенные и готовые к работе кандидаты каждый раз.',
        // Hero stats rewrite
        heroStat3Value2: '50+',
        heroStat3Label2: 'АКТИВНЫХ КЛИЕНТОВ',
        heroStat4Value: 'Вся Индия',
        heroStat4Label: 'СИЛЬНАЯ СЕТЬ НАЙМА',
    },
    en: {
        home: 'Home',
        aboutUs: 'About Us',
        services: 'Services',
        blog: 'Blog',
        contactUs: 'Contact Us',
        cvBuilder: 'CV Builder',
        whatsappUs: 'WhatsApp Us',
        heroTitle1: 'WORKFORCE',
        heroTitle2: 'RUSSIA',
        heroTagline: 'Government Approved Recruitment Agency with Local Support in Moscow. We help Russian companies hire skilled manpower from India, Nepal & Indonesia.',
        heroCtaServices: 'Get Workforce Now',
        heroCtaContact: 'Talk to Expert (WhatsApp)',
        heroStat1Value: '500+',
        heroStat1Label: 'WORKERS DEPLOYED',
        heroStat2Value: '2022',
        heroStat2Label: 'RUSSIA OPERATIONS',
        heroStat3Value: '10+',
        heroStat3Label: 'YEARS EXPERIENCE',
        formName: 'Your Name',
        formEmail: 'Email Address',
        formPhone: 'Phone Number',
        formMessage: 'Message',
        formSubmit: 'Send Inquiry',
        formTitle: 'Quick Inquiry',
        aboutTitle: '• About Us',
        aboutPara1: 'Your Trusted Manpower Partner in Russia',
        aboutPara2: 'Taha Airwaves is a globally trusted manpower recruitment company specializing in supplying skilled and semi-skilled workforce to Russia. With strong local presence in Moscow and deep understanding of Russian labor laws, we ensure smooth, compliant and fast hiring solutions.',
        learnMore: 'Request Candidates',
        getInTouch: 'Get in touch',
        strengthTitle: 'Strategic',
        strengthTitleAccent: 'Workforce Solutions',
        strengthSubtitle: 'Streamlined recruitment with reliable deployment of skilled manpower within 7–15 days.',
        metric1Value: '500+',
        metric1Label: 'Workers Deployed',
        metric1Desc: 'Verified workforce deployed across Russian industries since 2022',
        metric2Value: '2022',
        metric2Label: 'Russia Operations',
        metric2Desc: 'Dedicated Moscow office serving the Russian market',
        metric3Value: '10+',
        metric3Label: 'Years Global Experience',
        metric3Desc: 'Government-licensed recruitment agency since 2015',
        metric4Value: '50+',
        metric4Label: 'Partner Companies',
        metric4Desc: 'Trusted by leading employers across multiple industries',
        howTitle: 'What Makes Us',
        howTitleAccent: 'Different',
        howSubtitle: 'Hire better. Deploy faster. Scale smarter.',
        step1Title: 'India to Russia Hiring Specialists',
        step1Desc: 'Focused expertise in recruiting Indian workforce specifically for Russia with deep market understanding.',
        step2Title: 'Dedicated Client Coordination',
        step2Desc: 'Personalized support for every client to ensure smooth communication and faster decision-making.',
        step3Title: '7–15 Days Fast Deployment',
        step3Desc: 'One of the fastest manpower deployment timelines in the industry.',
        step4Title: 'Industry-Specific Hiring Expertise',
        step4Desc: 'Specialized recruitment solutions tailored for construction, logistics, manufacturing, and service sectors.',
        step5Title: 'Pre-Verified & Job-Ready Workers',
        step5Desc: 'Candidates are screened, tested, and prepared before deployment to reduce hiring risks.',
        step6Title: 'Scalable Workforce Solutions',
        step6Desc: 'Ability to handle bulk hiring requirements efficiently for small to large-scale projects.',
        whatTitle: 'What Makes Us',
        whatTitleAccent: 'Different',
        whatSubtitle: 'We deliver skilled manpower from India to Russia — without delays',
        svc1Title: 'Overseas Recruitment',
        svc1Desc: 'End-to-end recruitment solutions for international employers seeking professional Indian workforce.',
        svc2Title: 'Bulk Manpower Hiring',
        svc2Desc: 'High-volume workforce mobilization with rapid turnaround for large-scale projects and operations.',
        svc3Title: 'Visa & Documentation',
        svc3Desc: 'Complete visa processing, document attestation, emigration clearance, and compliance management.',
        svc4Title: 'Deployment Support',
        svc4Desc: 'Seamless pre-departure orientation, travel coordination, and post-deployment follow-up services.',
        countriesTitle: 'India to',
        countriesTitleAccent: 'Russia',
        countriesSubtitle: 'Bridging India\'s workforce with Russia\'s industry needs through professional recruitment',
        sourcingHub: 'Sourcing & Recruitment Hub',
        headOffice: 'Head Office: New Delhi',
        deploymentPipeline: 'Deployment Pipeline',
        workersDeployed: 'Workers Deployed to Russia',
        operationsOffice: 'Office: Moscow',
        deploymentOps: 'Deployment & Operations',
        industriesTitle: 'INDUSTRIES WE',
        industriesTitleAccent: 'SERVE',
        industriesSubtitle: 'Specialized workforce solutions across high-demand sectors in Russia',
        indConstruction: 'Construction',
        indConstructionDesc: 'Skilled workers, masons, and site supervisors',
        indHospitality: 'Hospitality',
        indHospitalityDesc: 'Hotel staff, cleaners, and hospitality professionals',
        indLogistics: 'Logistics',
        indLogisticsDesc: 'Warehouse staff and supply chain workers',
        indHealthcare: 'Healthcare',
        indHealthcareDesc: 'Healthcare support staff and medical assistants',
        indManufacturing: 'Manufacturing',
        indManufacturingDesc: 'Factory workers, machine operators, and QC inspectors',
        indFacility: 'Facility Management',
        indFacilityDesc: 'Maintenance staff, janitors, and facility operators',
        indOilGas: 'Oil & Gas',
        indOilGasDesc: 'Drilling crew, pipeline workers, and refinery operators',
        indIT: 'IT & Telecom',
        indITDesc: 'IT support staff, network technicians, and engineers',
        indRetail: 'Retail & FMCG',
        indRetailDesc: 'Store associates, merchandisers, and sales executives',
        whyTitle: '• Why Russian Companies Choose Taha Airwaves?',
        whyDesc: 'Government-licensed, verified workforce deployment with end-to-end recruitment, visa processing, and compliance — trusted by employers across Russia.',
        whyItem1Title: 'Government Approved Agency',
        whyItem1Desc: 'Fully licensed and compliant recruitment agency ensuring safe and legal hiring from India.',
        whyItem2Title: 'Fast Workforce Deployment',
        whyItem2Desc: 'Get your workforce deployed within 7–15 days with our streamlined recruitment system.',
        whyItem3Title: 'Verified & Skilled Candidates',
        whyItem3Desc: 'All workers are pre-screened, trained, and verified to match your exact job requirements.',
        whyItem4Title: 'Strong Talent Network',
        whyItem4Desc: 'Access a large database of skilled and unskilled workers across multiple industries.',
        whyItem5Title: 'Cost-Effective Hiring',
        whyItem5Desc: 'Reduce hiring costs with competitive pricing and efficient manpower solutions.',
        whyItem6Title: 'Local Support in Moscow',
        whyItem6Desc: 'On-ground support in Moscow for coordination, communication, and smooth workforce management.',
        whyItem7Title: 'End-to-End Support',
        whyItem7Desc: 'From sourcing to deployment, we manage the complete recruitment process for you.',
        whyPart2Title: 'Hire better. Deploy faster. Scale smarter.',
        whyPart2Desc: 'We deliver skilled manpower from India to Russia — without delays.',
        whyStat1Number: '500+',
        whyStat1Label: 'Workers Deployed',
        whyStat2Number: '365',
        whyStat2Label: 'Days of Ongoing Support',
        testimonialsTitle: 'What Our',
        testimonialsTitleAccent: 'Clients Say',
        testimonialsSubtitle: 'Trusted by employers across Russia and the Gulf region',
        blogTitle: 'Latest',
        blogTitleAccent: 'Insights',
        blogSubtitle: 'Stay updated with industry trends, deployment guides, and Russian market insights',
        viewAllArticles: 'View All Articles',
        readMore: 'Read More',
        ctaSubtitle: 'GET STARTED TODAY',
        ctaTitle: 'Build Your Workforce — Faster Than Ever',
        ctaDesc: 'Access verified candidates within days and keep your business moving forward.',
        ctaBtn1: 'Get Proposal',
        ctaBtn2: 'WhatsApp Now',
        quickLinks: 'Quick Links',
        ourServices: 'Our Services',
        ourOffices: 'Our Offices',
        contact: 'Contact',
        footerDesc: 'Government-licensed manpower recruitment agency providing professional workforce deployment services for the Russian market.',
        svcCleaners: 'Cleaners',
        svcDrivers: 'Drivers',
        svcGeneral: 'General Workers',
        svcFactory: 'Factory Workers',
        svcTechnicians: 'Technicians',
        svcVisa: 'Visa & Immigration',
        svcOutsourcing: 'Employee Outsourcing',
        // CardCarousel section keys
        servicesOffered: 'Services',
        csvcSectionTitle: 'What We Offer for the Russian Market',
        csvc1Title: 'Overseas Recruitment',
        csvc1Desc: 'End-to-end recruitment solutions for Russian employers seeking skilled and professional Indian workforce.',
        csvc2Title: 'Bulk Manpower Hiring',
        csvc2Desc: 'High-volume workforce mobilization with rapid turnaround for large-scale construction and industrial projects.',
        csvc3Title: 'Visa & Documentation',
        csvc3Desc: 'Complete visa processing, document attestation, emigration clearance, and compliance management end-to-end.',
        csvc4Title: 'Deployment Support',
        csvc4Desc: 'Pre-departure orientation, travel coordination, and post-deployment follow-up services.',
        csvc5Title: 'Employee Outsourcing',
        csvc5Desc: 'Complete workforce outsourcing — staffing, payroll management, and HR compliance handled end-to-end.',
        csvcBottomDesc: 'From skilled workers to bulk manpower for mega-projects — full documentation, visa processing, and deployment support for Russia.',
        viewAllServices: 'All Services',
        // HomeServiceBento
        bentoTitle: 'Our Recruitment Process',
        bentoStep1: 'Requirement Analysis',
        bentoStep1Desc: 'Understanding your workforce needs, job roles, and project requirements to ensure the right hiring strategy.',
        bentoStep2: 'Sourcing & Screening',
        bentoStep2Desc: 'We source candidates from India\'s top talent pools and conduct strict screening and background verification.',
        bentoStep3: 'Skill Assessment',
        bentoStep3Desc: 'Trade testing and practical evaluations to ensure candidates meet industry standards and job expectations.',
        bentoStep4: 'Documentation & Visa',
        bentoStep4Desc: 'Complete handling of visa processing, legal compliance, and documentation for smooth international hiring.',
        bentoStep5: 'Deployment & Travel',
        bentoStep5Desc: 'Pre-departure briefing, travel arrangements, and seamless deployment to your project location.',
        bentoStep6: 'Ongoing Support',
        bentoStep6Desc: 'Continuous support with clear communication, reporting, and zero hidden charges throughout the process.',
        bentoCTA1: 'Hire better. Deploy faster. Scale smarter.',
        bentoCTA2: 'We deliver skilled manpower from India to Russia — without delays',
        // ServicesShowcase
        sspTitle: 'Our Manpower Services for Russia',
        pSvc1Title: 'Cleaners & Housekeeping',
        pSvc1Desc: 'Professionally trained staff for hotels, hospitals, commercial complexes, and residential facilities across Russia.',
        pSvc2Title: 'All Types of Drivers',
        pSvc2Desc: 'Licensed drivers for light and heavy vehicles, construction equipment, and specialized transport.',
        pSvc3Title: 'General Labour',
        pSvc3Desc: 'Reliable labourers for construction sites, warehouses, factories, and infrastructure projects in Russia.',
        pSvc4Title: 'Factory Helpers',
        pSvc4Desc: 'Trained assistants for manufacturing, assembly lines, packaging, QC, and production support.',
        pSvc5Title: 'Emigration Clearance',
        pSvc5Desc: 'Complete visa processing, documentation, emigration clearance and compliance management for Russia.',
        pSvc6Title: 'Employee Outsourcing',
        pSvc6Desc: 'Complete HR outsourcing — temporary and permanent staffing with payroll and compliance end-to-end.',
        hireManpower: 'Hire Manpower',
        // Industries extended
        indAgriculture: 'Agriculture',
        indAgricultureDesc: 'Farm labourers and harvest specialists',
        indMining: 'Mining',
        indMiningDesc: 'Miners, drillers, and plant operators',
        // CountriesWeServe additional
        additionalCountries: 'Additional Markets',
        // Sub-pages
        pageServicesTitle: 'Our Services',
        pageServicesSubtitle: 'Comprehensive workforce solutions for the Russian market',
        pageBlogTitle: 'Journal',
        pageBlogSubtitle: 'Russian labour market insights and deployment guides',
        // About page
        ourServices: 'Services',
        aboutStatLabel1: 'Workers Deployed',
        aboutStatLabel2: 'Years Experience',
        aboutStatLabel3: 'Partner Companies',
        aboutStatLabel4: 'Compliance Rate',
        missionTitle: 'Our Mission',
        missionDesc: 'To bridge India\'s talent pool with Russia\'s workforce demand, providing reliable, compliant, and efficient manpower recruitment services that empower workers and satisfy employers.',
        visionTitle: 'Our Vision',
        visionDesc: 'To be the most trusted manpower recruitment agency for the Russian market, known for quality, transparency, and end-to-end deployment of verified professionals.',
        promiseTitle: 'Our Promise',
        promiseDesc: 'Government-licensed, trade-tested, and fully documented workforce — delivered on time, every time, without shortcuts or compromises.',
        // Additional services (ServicesMain)
        loadingTitle: 'Loading & Unloading',
        loadingDesc: 'Experienced cargo handlers for ports, warehouses, freight terminals, and distribution centres.',
        baristaTitle: 'Barista Workers',
        baristaDesc: 'Trained baristas for cafés, hotels, resorts, events, and corporate food courts.',
        packersTitle: 'Packing Workers',
        packersDesc: 'Packing, sorting, labelling, quality control, and container packing workforce.',
        docAttestTitle: 'Document Attestation',
        docAttestDesc: 'State, MEA, and embassy attestation for educational, professional, and commercial documents.',
        techDesc: 'Qualified technicians, electricians, and specialists for construction and industrial projects.',
        // Contact form
        formName: 'Your Name',
        formEmail: 'Your Email',
        formPhone: 'Phone Number',
        formSubmit: 'Send Message',

        chatWelcome: "Hello! I'm the Taha Airwaves assistant. How can I help you today? Whether you're an employer looking for manpower or a job seeker, I'm here to guide you.",
        chatQuick1: 'What services do you offer?',
        chatQuick2: 'How fast is deployment?',
        chatQuick3: 'Which countries do you serve?',
        chatQuick4: 'I want to hire workers',
        chatPlaceholder: 'Type a message...',
        chatTooltip: 'Ask Taha AI',
        chatOnline: 'AI Assistant • Online',
        partnersTitle: 'Our',
        partnersTitleAccent: 'Partners',
        partnersSubtitle: 'Trusted by leading companies',
        // Stats — Bento rewrite
        bentoStatTitle1: 'Taha Airwaves: Driven by Speed',
        bentoStatDesc1: 'Fast hiring and deployment without compromising quality.',
        bentoStatTitle2: 'Taha Airwaves: Focused on Quality',
        bentoStatDesc2: 'Skilled, verified, and job-ready candidates every time.',
        // Hero stats rewrite
        heroStat3Value2: '50+',
        heroStat3Label2: 'ACTIVE CLIENTS',
        heroStat4Value: 'Pan-India',
        heroStat4Label: 'RECRUITMENT NETWORK',
    }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('ru') // Russian by default

    const t = (key) => translations[lang]?.[key] || translations.en[key] || key

    const toggleLang = () => setLang(prev => prev === 'ru' ? 'en' : 'ru')

    return (
        <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const ctx = useContext(LanguageContext)
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
    return ctx
}
