'use client'

import { createContext, useContext, useState } from 'react'

const translations = {
    ru: {
        // Navbar
        home: 'Главная',
        aboutUs: 'О нас',
        services: 'Услуги',
        blog: 'Блог',
        contactUs: 'Контакты',
        whatsappUs: 'Написать в WhatsApp',
        // Hero
        heroTitle1: 'КАДРОВЫЕ',
        heroTitle2: 'РЕШЕНИЯ',
        heroTagline: 'Профессиональный подбор и предоставление персонала для российского рынка',
        heroCtaServices: 'Наши услуги',
        heroCtaContact: 'Связаться с нами',
        heroStat1Value: '500+',
        heroStat1Label: 'РАБОТНИКОВ В РОССИИ',
        heroStat2Value: '2022',
        heroStat2Label: 'РАБОТА В РОССИИ',
        heroStat3Value: '20+',
        heroStat3Label: 'ЛЕТ ОПЫТА',
        // Hero Contact Form
        formName: 'Ваше имя',
        formEmail: 'Эл. почта',
        formPhone: 'Телефон',
        formMessage: 'Сообщение',
        formSubmit: 'Отправить заявку',
        formTitle: 'Быстрая заявка',
        // About
        aboutTitle: '• О нас',
        aboutPara1: 'Лицензированное государством агентство по подбору персонала, предоставляющее проверенные кадровые решения для российского рынка с 2022 года.',
        aboutPara2: 'Taha Airwaves Private Limited специализируется на комплексных услугах по подбору персонала — от поиска и отбора кандидатов до оформления виз, документации и размещения. С выделенной командой для работы в России и более чем 20-летним мировым опытом.',
        learnMore: 'Подробнее',
        getInTouch: 'Связаться',
        // Our Strength
        strengthTitle: 'Наши',
        strengthTitleAccent: 'достижения',
        strengthSubtitle: 'Ключевые показатели нашей работы в России',
        metric1Value: '500+',
        metric1Label: 'Сотрудников в России',
        metric1Desc: 'Проверенные специалисты, размещённые в различных отраслях с 2022 года',
        metric2Value: '2022',
        metric2Label: 'Начало работы в России',
        metric2Desc: 'Офис в Москве, обслуживающий российский рынок',
        metric3Value: '20+',
        metric3Label: 'Лет мирового опыта',
        metric3Desc: 'Лицензированное агентство по набору персонала с 2005 года',
        metric4Value: '50+',
        metric4Label: 'Компаний-партнёров',
        metric4Desc: 'Работаем с ведущими работодателями в различных отраслях',
        // How It Works
        howTitle: 'Как мы',
        howTitleAccent: 'работаем',
        howSubtitle: 'Оптимизированный 4-этапный процесс от заявки до размещения',
        step1Title: 'Анализ потребностей',
        step1Desc: 'Сообщите нам о ваших кадровых потребностях — роль, количество, локация.',
        step2Title: 'Поиск и отбор',
        step2Desc: 'Мы находим, проверяем и отбираем кандидатов через структурированные собеседования и оценку навыков.',
        step3Title: 'Документация и виза',
        step3Desc: 'Все документы, медосмотры, эмиграционное оформление и визовая обработка — под ключ.',
        step4Title: 'Размещение',
        step4Desc: 'Предвыездная ориентация, организация перелёта, размещение и последующая поддержка.',
        // What We Do
        whatTitle: 'Что мы',
        whatTitleAccent: 'делаем',
        whatSubtitle: 'Комплексные кадровые услуги, охватывающие все этапы рекрутинга',
        svc1Title: 'Подбор персонала',
        svc1Desc: 'Комплексные решения по подбору для международных работодателей, ищущих индийских специалистов.',
        svc2Title: 'Массовый набор',
        svc2Desc: 'Высокообъёмная мобилизация рабочей силы с быстрыми сроками для крупных проектов.',
        svc3Title: 'Визы и документы',
        svc3Desc: 'Полная визовая обработка, заверение документов, эмиграционное оформление и управление соответствием.',
        svc4Title: 'Поддержка развёртывания',
        svc4Desc: 'Предвыездная подготовка, координация поездок и послеразмещённая поддержка.',
        // Countries
        countriesTitle: 'Индия —',
        countriesTitleAccent: 'Россия',
        countriesSubtitle: 'Мост между индийскими кадрами и потребностями российской промышленности',
        sourcingHub: 'Центр подбора',
        headOffice: 'Головной офис: Нью-Дели',
        deploymentPipeline: 'Канал развёртывания',
        workersDeployed: 'Работников размещено в России',
        operationsOffice: 'Офис: Москва',
        deploymentOps: 'Развёртывание и операции',
        // Industries
        industriesTitle: 'Отрасли, которые мы',
        industriesTitleAccent: 'обслуживаем',
        industriesSubtitle: 'Специализированные кадровые решения для ключевых секторов России',
        indConstruction: 'Строительство',
        indConstructionDesc: 'Рабочие, каменщики и прорабы',
        indHospitality: 'Гостеприимство',
        indHospitalityDesc: 'Персонал отелей, уборщики и работники гостиниц',
        indLogistics: 'Логистика',
        indLogisticsDesc: 'Складские сотрудники и работники цепочки поставок',
        indHealthcare: 'Здравоохранение',
        indHealthcareDesc: 'Вспомогательный медицинский персонал',
        indManufacturing: 'Производство',
        indManufacturingDesc: 'Рабочие фабрик, операторы машин и инспекторы',
        indFacility: 'Управление объектами',
        indFacilityDesc: 'Технический персонал и операторы объектов',
        indOilGas: 'Нефть и газ',
        indOilGasDesc: 'Буровые бригады и работники нефтепровода',
        indIT: 'ИТ и телеком',
        indITDesc: 'ИТ-поддержка, сетевые техники и инженеры',
        indRetail: 'Торговля и FMCG',
        indRetailDesc: 'Торговые ассоциаты и мерчандайзеры',
        // Why Us
        whyTitle: '• Почему мы',
        whyDesc: 'Лицензированное государством развёртывание проверенных кадров с полным циклом рекрутинга, визовой обработкой и соответствием — доверие работодателей по всей России.',
        whyItem1Title: 'Государственная лицензия',
        whyItem1Desc: 'Полная лицензия Министерства иностранных дел Индии. Лицензия RA № B-3260/DEL/COM/100/5/11259/2025 — 100% легальный и соответствующий набор.',
        whyItem2Title: 'Проверенные кадры',
        whyItem2Desc: 'Каждый кандидат проходит тщательную проверку навыков и биографии перед размещением — гарантия качества для российских работодателей.',
        whyItem3Title: 'Экспертиза по России',
        whyItem3Desc: 'Выделенный московский офис со специализированной командой для российского рынка с 2022 года.',
        whyPart2Title: 'Десятилетия доверия в развёртывании кадров для России',
        whyPart2Desc: 'С более чем 20-летним опытом в сфере зарубежного набора персонала и выделенной командой для России с 2022 года, Taha Airwaves заработала репутацию надёжности, скорости и соответствия на российском рынке.',
        whyStat1Number: '500+',
        whyStat1Label: 'Работников в России',
        whyStat2Number: '20+',
        whyStat2Label: 'Лет опыта',
        // Testimonials
        testimonialsTitle: 'Что говорят наши',
        testimonialsTitleAccent: 'клиенты',
        testimonialsSubtitle: 'Нам доверяют работодатели по всей России',
        // Blog
        blogTitle: 'Последние',
        blogTitleAccent: 'публикации',
        blogSubtitle: 'Актуальные тренды, руководства и аналитика российского рынка',
        viewAllArticles: 'Все статьи',
        readMore: 'Читать далее',
        // CTA
        ctaSubtitle: 'Набор персонала для России',
        ctaTitle: 'Готовы сформировать команду в России?',
        // Footer
        quickLinks: 'Быстрые ссылки',
        ourServices: 'Наши услуги',
        ourOffices: 'Наши офисы',
        contact: 'Контакты',
        footerDesc: 'Лицензированное государством агентство по подбору персонала, предоставляющее профессиональные кадровые решения для российского рынка.',
        // Footer service links
        svcCleaners: 'Уборщики',
        svcDrivers: 'Водители',
        svcGeneral: 'Общий труд',
        svcFactory: 'Рабочие фабрик',
        svcTechnicians: 'Техники',
        svcVisa: 'Виза и миграция',
        svcOutsourcing: 'Аутсорсинг персонала',
        // CardCarousel section keys
        servicesOffered: 'Услуги',
        csvcSectionTitle: 'Что мы предлагаем российскому рынку',
        csvc1Title: 'Международный рекрутинг',
        csvc1Desc: 'Комплексный подбор персонала для российских работодателей, ищущих квалифицированных индийских специалистов.',
        csvc2Title: 'Массовый найм',
        csvc2Desc: 'Крупномасштабная мобилизация рабочей силы с быстрыми сроками для строительных и промышленных проектов.',
        csvc3Title: 'Виза и документы',
        csvc3Desc: 'Полная визовая обработка, заверение документов, эмиграционное оформление и соответствие — под ключ.',
        csvc4Title: 'Поддержка развёртывания',
        csvc4Desc: 'Предвыездная подготовка, координация поездок и послеразмещённая поддержка.',
        csvc5Title: 'Аутсорсинг сотрудников',
        csvc5Desc: 'Полные решения по кадровому аутсорсингу — подбор персонала, расчёт зарплат и соответствие HR.',
        csvcBottomDesc: 'От квалифицированных рабочих до массового найма для крупных проектов — полная документация, визовая обработка и поддержка развёртывания.',
        viewAllServices: 'Все услуги',
        // HomeServiceBento
        bentoTitle: 'Как мы работаем',
        bentoStep1: 'Поиск и отбор',
        bentoStep1Desc: 'Проверенные кандидаты из крупнейшего кадрового резерва Индии',
        bentoStep2: 'Проверка навыков',
        bentoStep2Desc: 'Строгая оценка компетенций и проверка биографии',
        bentoStep3: 'Виза и документы',
        bentoStep3Desc: 'Комплексное визовое оформление и соответствие требованиям',
        bentoStep4: 'Развёртывание',
        bentoStep4Desc: 'Предвыездная ориентация и координация поездки',
        bentoCTA1: 'Комплексные кадровые решения, связывающие таланты Индии с российским спросом',
        bentoCTA2: 'От поиска до размещения — мы управляем полным циклом рекрутинга',
        // ServicesShowcase
        sspTitle: 'Наши кадровые услуги для России',
        pSvc1Title: 'Уборщики и клининг',
        pSvc1Desc: 'Профессионально обученный персонал для отелей, больниц, коммерческих и жилых объектов России.',
        pSvc2Title: 'Водители всех категорий',
        pSvc2Desc: 'Лицензированные водители для лёгкого и тяжёлого транспорта, строительной техники и специализированного транспорта.',
        pSvc3Title: 'Разнорабочие',
        pSvc3Desc: 'Надёжные рабочие для строительных площадок, складов, заводов и инфраструктурных проектов в России.',
        pSvc4Title: 'Помощники на заводе',
        pSvc4Desc: 'Обученные ассистенты для производственных линий, упаковки, контроля качества и производственной поддержки.',
        pSvc5Title: 'Оформление эмиграции',
        pSvc5Desc: 'Полное визовое оформление, документация, эмиграционное разрешение и управление соответствием для России.',
        pSvc6Title: 'Аутсорсинг персонала',
        pSvc6Desc: 'Комплексное кадровое обеспечение — временный и постоянный штат, расчёт зарплат и соответствие.',
        hireManpower: 'Нанять персонал',
        // Industries extended
        indAgriculture: 'Сельское хозяйство',
        indAgricultureDesc: 'Сельскохозяйственные рабочие и специалисты по сбору урожая',
        indMining: 'Горнодобывающая',
        indMiningDesc: 'Горняки, взрывники и операторы',
        // CountriesWeServe additional
        additionalCountries: 'Другие рынки',
        // Sub-pages
        pageServicesTitle: 'Наши услуги',
        pageServicesSubtitle: 'Комплексные кадровые решения для российского рынка',
        pageBlogTitle: 'Журнал',
        pageBlogSubtitle: 'Аналитика российского рынка труда и руководства по развёртыванию',
        // About page
        ourServices: 'Услуги',
        aboutStatLabel1: 'Работники в России',
        aboutStatLabel2: 'Лет опыта',
        aboutStatLabel3: 'Партнёрские компании',
        aboutStatLabel4: 'Соответствие',
        missionTitle: 'Наша миссия',
        missionDesc: 'Связать огромный кадровый потенциал Индии с российским спросом на рабочую силу, обеспечивая надёжный, соответствующий и эффективный рекрутинг.',
        visionTitle: 'Наше видение',
        visionDesc: 'Стать самым надёжным агентством по подбору персонала для российского рынка, известным своей качеством, прозрачностью и комплексным обслуживанием.',
        promiseTitle: 'Наше обещание',
        promiseDesc: 'Лицензированная, прошедшая трейд тестирование и полностью документированная рабочая сила — доставленная вовремя без компромиссов.',
        // Additional services (ServicesMain)
        loadingTitle: 'Грузчики',
        loadingDesc: 'Опытные грузчики для портов, складов, фрахтовых терминалов и дистрибьюцентров.',
        baristaTitle: 'Баристы',
        baristaDesc: 'Обученные баристы для кафе, отелей, корпоративных мероприятий.',
        packersTitle: 'Упаковщики',
        packersDesc: 'Упаковка, сортировка, маркировка и контроль качества.',
        docAttestTitle: 'Аттестация документов',
        docAttestDesc: 'Аттестация через министерство, MEA и посольство для учебных, профессиональных и коммерческих документов.',
        techDesc: 'Квалифицированные техники, электрики и специалисты для строительных проектов.',
        // Contact form
        formName: 'Ваше имя',
        formEmail: 'Эл. почта',
        formPhone: 'Номер телефона',
        formSubmit: 'Отправить',

        // Chatbot
        chatWelcome: 'Здравствуйте! Я ассистент Taha Airwaves. Чем могу помочь? Буду рад помочь работодателям в подборе персонала или соискателям о доступных вакансиях.',
        chatQuick1: 'Какие услуги вы предлагаете?',
        chatQuick2: 'Как быстро происходит трудоустройство?',
        chatQuick3: 'В какие страны вы осуществляете набор?',
        chatQuick4: 'Хочу нанять работников',
        chatPlaceholder: 'Напишите сообщение...',
        chatTooltip: 'Спросите у ИИ Taha',
        chatOnline: 'ИИ-ассистент • Онлайн',
        // Partners
        partnersTitle: 'Наши',
        partnersTitleAccent: 'партнёры',
        partnersSubtitle: 'Нам доверяют ведущие компании',
    },
    en: {
        home: 'Home',
        aboutUs: 'About Us',
        services: 'Services',
        blog: 'Blog',
        contactUs: 'Contact Us',
        whatsappUs: 'WhatsApp Us',
        heroTitle1: 'WORKFORCE',
        heroTitle2: 'RUSSIA',
        heroTagline: 'Premier manpower recruitment and deployment services for the Russian market',
        heroCtaServices: 'Our Services',
        heroCtaContact: 'Get in Touch',
        heroStat1Value: '500+',
        heroStat1Label: 'WORKERS IN RUSSIA',
        heroStat2Value: '2022',
        heroStat2Label: 'RUSSIA OPERATIONS',
        heroStat3Value: '20+',
        heroStat3Label: 'YEARS EXPERIENCE',
        formName: 'Your Name',
        formEmail: 'Email Address',
        formPhone: 'Phone Number',
        formMessage: 'Message',
        formSubmit: 'Send Inquiry',
        formTitle: 'Quick Inquiry',
        aboutTitle: '• About Us',
        aboutPara1: 'Government-licensed manpower recruitment agency delivering verified, deployment-ready workforce solutions exclusively for the Russian market since 2022.',
        aboutPara2: 'Taha Airwaves Private Limited specializes in end-to-end recruitment services — from sourcing and screening candidates to visa processing, documentation, and deployment. With a dedicated Russia operations team and 20+ years of global experience.',
        learnMore: 'Learn More',
        getInTouch: 'Get in touch',
        strengthTitle: 'Our',
        strengthTitleAccent: 'Strength',
        strengthSubtitle: 'Key metrics that define our commitment to workforce excellence in Russia',
        metric1Value: '500+',
        metric1Label: 'Workers in Russia',
        metric1Desc: 'Verified workforce deployed across Russian industries since 2022',
        metric2Value: '2022',
        metric2Label: 'Russia Operations',
        metric2Desc: 'Dedicated Moscow office serving the Russian market',
        metric3Value: '20+',
        metric3Label: 'Years Global Experience',
        metric3Desc: 'Government-licensed recruitment agency since 2005',
        metric4Value: '50+',
        metric4Label: 'Partner Companies',
        metric4Desc: 'Trusted by leading employers across multiple industries',
        howTitle: 'How It',
        howTitleAccent: 'Works',
        howSubtitle: 'A streamlined 4-step process from requirement to deployment',
        step1Title: 'Requirement Analysis',
        step1Desc: 'Share your manpower needs — role, quantity, location — and our team creates a tailored recruitment plan.',
        step2Title: 'Sourcing & Screening',
        step2Desc: 'We source, verify, and shortlist candidates through structured interviews, skill assessments, and background checks.',
        step3Title: 'Documentation & Visa',
        step3Desc: 'All paperwork, medical exams, emigration clearance, and visa processing handled end-to-end with 100% compliance.',
        step4Title: 'Deployment & Travel',
        step4Desc: 'Pre-departure orientation, flight arrangements, smooth deployment, and post-deployment follow-up.',
        whatTitle: 'What We',
        whatTitleAccent: 'Do',
        whatSubtitle: 'Comprehensive manpower services covering every phase of the recruitment lifecycle',
        svc1Title: 'Overseas Recruitment',
        svc1Desc: 'End-to-end recruitment solutions for international employers seeking professional Indian workforce.',
        svc2Title: 'Bulk Manpower Hiring',
        svc2Desc: 'High-volume workforce mobilization with rapid turnaround for large-scale projects and operations.',
        svc3Title: 'Visa & Documentation',
        svc3Desc: 'Complete visa processing, document attestation, emigration clearance, and compliance management.',
        svc4Title: 'Deployment Support',
        svc4Desc: 'Seamless pre-departure orientation, travel coordination, and post-deployment follow-up services.',
        countriesTitle: 'India to',
        countriesTitleAccent: 'Russia',
        countriesSubtitle: 'Bridging India\'s workforce with Russia\'s industry needs through professional recruitment',
        sourcingHub: 'Sourcing & Recruitment Hub',
        headOffice: 'Head Office: New Delhi',
        deploymentPipeline: 'Deployment Pipeline',
        workersDeployed: 'Workers Deployed to Russia',
        operationsOffice: 'Office: Moscow',
        deploymentOps: 'Deployment & Operations',
        industriesTitle: 'Industries We',
        industriesTitleAccent: 'Serve',
        industriesSubtitle: 'Specialized workforce solutions across high-demand sectors in Russia',
        indConstruction: 'Construction',
        indConstructionDesc: 'Skilled workers, masons, and site supervisors',
        indHospitality: 'Hospitality',
        indHospitalityDesc: 'Hotel staff, cleaners, and hospitality professionals',
        indLogistics: 'Logistics',
        indLogisticsDesc: 'Warehouse staff and supply chain workers',
        indHealthcare: 'Healthcare',
        indHealthcareDesc: 'Healthcare support staff and medical assistants',
        indManufacturing: 'Manufacturing',
        indManufacturingDesc: 'Factory workers, machine operators, and QC inspectors',
        indFacility: 'Facility Management',
        indFacilityDesc: 'Maintenance staff, janitors, and facility operators',
        indOilGas: 'Oil & Gas',
        indOilGasDesc: 'Drilling crew, pipeline workers, and refinery operators',
        indIT: 'IT & Telecom',
        indITDesc: 'IT support staff, network technicians, and engineers',
        indRetail: 'Retail & FMCG',
        indRetailDesc: 'Store associates, merchandisers, and sales executives',
        whyTitle: '• Why Choose Us',
        whyDesc: 'Government-licensed, verified workforce deployment with end-to-end recruitment, visa processing, and compliance — trusted by employers across Russia.',
        whyItem1Title: 'Government Licensed',
        whyItem1Desc: 'Fully licensed by the Ministry of External Affairs, India. RA License No. B-3260/DEL/COM/100/5/11259/2025 — ensuring 100% legal and compliant recruitment.',
        whyItem2Title: 'Verified Workforce',
        whyItem2Desc: 'Every candidate undergoes rigorous trade testing, verification, and background checks before deployment — guaranteeing quality manpower to Russian employers.',
        whyItem3Title: 'Russia Expertise',
        whyItem3Desc: 'Dedicated Moscow office with a specialized team for the Russian market since 2022. Deep understanding of Russian employment regulations.',
        whyPart2Title: 'Decades of Trust in Workforce Deployment for Russia',
        whyPart2Desc: 'With 20+ years in the overseas manpower industry and a dedicated Russia operations team since 2022, Taha Airwaves has built a reputation for reliability, speed, and compliance in the Russian market.',
        whyStat1Number: '500+',
        whyStat1Label: 'Workers in Russia',
        whyStat2Number: '20+',
        whyStat2Label: 'Years Experience',
        testimonialsTitle: 'What Our',
        testimonialsTitleAccent: 'Clients Say',
        testimonialsSubtitle: 'Trusted by employers across Russia and the Gulf region',
        blogTitle: 'Latest',
        blogTitleAccent: 'Insights',
        blogSubtitle: 'Stay updated with industry trends, deployment guides, and Russian market insights',
        viewAllArticles: 'View All Articles',
        readMore: 'Read More',
        ctaSubtitle: 'Manpower Recruitment for Russia',
        ctaTitle: 'Ready to Build Your Workforce in Russia?',
        quickLinks: 'Quick Links',
        ourServices: 'Our Services',
        ourOffices: 'Our Offices',
        contact: 'Contact',
        footerDesc: 'Government-licensed manpower recruitment agency providing professional workforce deployment services for the Russian market.',
        svcCleaners: 'Cleaners',
        svcDrivers: 'Drivers',
        svcGeneral: 'General Workers',
        svcFactory: 'Factory Workers',
        svcTechnicians: 'Technicians',
        svcVisa: 'Visa & Immigration',
        svcOutsourcing: 'Employee Outsourcing',
        // CardCarousel section keys
        servicesOffered: 'Services',
        csvcSectionTitle: 'What We Offer for the Russian Market',
        csvc1Title: 'Overseas Recruitment',
        csvc1Desc: 'End-to-end recruitment solutions for Russian employers seeking skilled and professional Indian workforce.',
        csvc2Title: 'Bulk Manpower Hiring',
        csvc2Desc: 'High-volume workforce mobilization with rapid turnaround for large-scale construction and industrial projects.',
        csvc3Title: 'Visa & Documentation',
        csvc3Desc: 'Complete visa processing, document attestation, emigration clearance, and compliance management end-to-end.',
        csvc4Title: 'Deployment Support',
        csvc4Desc: 'Pre-departure orientation, travel coordination, and post-deployment follow-up services.',
        csvc5Title: 'Employee Outsourcing',
        csvc5Desc: 'Complete workforce outsourcing — staffing, payroll management, and HR compliance handled end-to-end.',
        csvcBottomDesc: 'From skilled workers to bulk manpower for mega-projects — full documentation, visa processing, and deployment support for Russia.',
        viewAllServices: 'All Services',
        // HomeServiceBento
        bentoTitle: 'How We Work',
        bentoStep1: 'Source & Screen',
        bentoStep1Desc: 'Verified candidates from India\'s largest talent pool',
        bentoStep2: 'Trade Testing',
        bentoStep2Desc: 'Rigorous skill assessments and background verification',
        bentoStep3: 'Visa & Docs',
        bentoStep3Desc: 'End-to-end visa processing and compliance',
        bentoStep4: 'Deploy',
        bentoStep4Desc: 'Pre-departure orientation and travel coordination',
        bentoCTA1: 'Comprehensive manpower solutions bridging India\'s talent with Russia\'s demand',
        bentoCTA2: 'From sourcing to deployment — we handle the complete recruitment lifecycle',
        // ServicesShowcase
        sspTitle: 'Our Manpower Services for Russia',
        pSvc1Title: 'Cleaners & Housekeeping',
        pSvc1Desc: 'Professionally trained staff for hotels, hospitals, commercial complexes, and residential facilities across Russia.',
        pSvc2Title: 'All Types of Drivers',
        pSvc2Desc: 'Licensed drivers for light and heavy vehicles, construction equipment, and specialized transport.',
        pSvc3Title: 'General Labour',
        pSvc3Desc: 'Reliable labourers for construction sites, warehouses, factories, and infrastructure projects in Russia.',
        pSvc4Title: 'Factory Helpers',
        pSvc4Desc: 'Trained assistants for manufacturing, assembly lines, packaging, QC, and production support.',
        pSvc5Title: 'Emigration Clearance',
        pSvc5Desc: 'Complete visa processing, documentation, emigration clearance and compliance management for Russia.',
        pSvc6Title: 'Employee Outsourcing',
        pSvc6Desc: 'Complete HR outsourcing — temporary and permanent staffing with payroll and compliance end-to-end.',
        hireManpower: 'Hire Manpower',
        // Industries extended
        indAgriculture: 'Agriculture',
        indAgricultureDesc: 'Farm labourers and harvest specialists',
        indMining: 'Mining',
        indMiningDesc: 'Miners, drillers, and plant operators',
        // CountriesWeServe additional
        additionalCountries: 'Additional Markets',
        // Sub-pages
        pageServicesTitle: 'Our Services',
        pageServicesSubtitle: 'Comprehensive workforce solutions for the Russian market',
        pageBlogTitle: 'Journal',
        pageBlogSubtitle: 'Russian labour market insights and deployment guides',
        // About page
        ourServices: 'Services',
        aboutStatLabel1: 'Workers in Russia',
        aboutStatLabel2: 'Years Experience',
        aboutStatLabel3: 'Partner Companies',
        aboutStatLabel4: 'Compliance Rate',
        missionTitle: 'Our Mission',
        missionDesc: 'To bridge India\'s talent pool with Russia\'s workforce demand, providing reliable, compliant, and efficient manpower recruitment services that empower workers and satisfy employers.',
        visionTitle: 'Our Vision',
        visionDesc: 'To be the most trusted manpower recruitment agency for the Russian market, known for quality, transparency, and end-to-end deployment of verified professionals.',
        promiseTitle: 'Our Promise',
        promiseDesc: 'Government-licensed, trade-tested, and fully documented workforce — delivered on time, every time, without shortcuts or compromises.',
        // Additional services (ServicesMain)
        loadingTitle: 'Loading & Unloading',
        loadingDesc: 'Experienced cargo handlers for ports, warehouses, freight terminals, and distribution centres.',
        baristaTitle: 'Barista Workers',
        baristaDesc: 'Trained baristas for cafés, hotels, resorts, events, and corporate food courts.',
        packersTitle: 'Packing Workers',
        packersDesc: 'Packing, sorting, labelling, quality control, and container packing workforce.',
        docAttestTitle: 'Document Attestation',
        docAttestDesc: 'State, MEA, and embassy attestation for educational, professional, and commercial documents.',
        techDesc: 'Qualified technicians, electricians, and specialists for construction and industrial projects.',
        // Contact form
        formName: 'Your Name',
        formEmail: 'Your Email',
        formPhone: 'Phone Number',
        formSubmit: 'Send Message',

        chatWelcome: "Hello! I'm the Taha Airwaves assistant. How can I help you today? Whether you're an employer looking for manpower or a job seeker, I'm here to guide you.",
        chatQuick1: 'What services do you offer?',
        chatQuick2: 'How fast is deployment?',
        chatQuick3: 'Which countries do you serve?',
        chatQuick4: 'I want to hire workers',
        chatPlaceholder: 'Type a message...',
        chatTooltip: 'Ask Taha AI',
        chatOnline: 'AI Assistant • Online',
        partnersTitle: 'Our',
        partnersTitleAccent: 'Partners',
        partnersSubtitle: 'Trusted by leading companies',
    }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('ru') // Russian by default

    const t = (key) => translations[lang]?.[key] || translations.en[key] || key

    const toggleLang = () => setLang(prev => prev === 'ru' ? 'en' : 'ru')

    return (
        <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const ctx = useContext(LanguageContext)
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
    return ctx
}
